export const ARTICLES_REQUEST = 'ARTICLES_REQUEST';
export const ARTICLES_FAILURE = 'ARTICLES_FAILURE';
export const ARTICLES_SUCCESS = 'ARTICLES_SUCCESS';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
