export const GET_REQUEST = 'GET_REQUEST';
export const GET_SUCCESS = 'GET_SUCCESS';
export const GET_FAILURE = 'GET_FAILURE';

export const FOLLOW_USER_FAILURE = 'FOLLOW_USER_FAILURE';
export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';

export const FOLLOWERS_REQUEST = 'FOLLOWERS_REQUEST';
export const FOLLOWERS_SUCCESS = 'FOLLOWERS_SUCCESS';
export const FOLLOWERS_FAILURE = 'FOLLOWERS_FAILURE';

export const FOLLOWING_REQUEST = 'FOLLOWING_REQUEST';
export const FOLLOWING_SUCCESS = 'FOLLOWING_SUCCESS';
export const FOLLOWING_FAILURE = 'FOLLOWING_FAILURE';

export const UPDATE_PROFILE_NOTIFICATION_SUCCESS = 'UPDATE_PROFILE_NOTIFICATION_SUCCESS';
export const UPDATE_PROFILE_NOTIFICATION_REQUEST = 'UPDATE_PROFILE_NOTIFICATION_REQUEST';
